---
apiVersion: v1
kind: Pod
metadata:
  name: busybox-cfg
spec:
  containers:
  - image: busybox
    name: busybox
    command:
    - /bin/sh
    - -c
    - "cat /opt/app/messages/message && sleep 1000"
    volumeMounts:
    - name: cfg-mount
      mountPath: "/opt/app/messages"
  restartPolicy: Never
  volumes:
  - name: cfg-mount
    configMap:
      name: busybox-config

